# Generated by Django 5.2.17 on 2026-10-03 14:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0003_pricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('25000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reserved_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=9)),
                ('quantity', models.PositiveIntegerField()),
                ('submission_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reserved_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reserved_shares', models.PositiveIntegerField(default=0)),
                ('execution_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.stock')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='market.stock')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trading.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INITIAL_BALANCE', 'Initial balance'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='trading.order')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='trading.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('cash_balance__gte', Decimal('0.00'))), name='cash_balance_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_cash__gte', Decimal('0.00'))), name='reserved_cash_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_cash__lte', models.F('cash_balance'))), name='reserved_cash_not_exceed_cash_balance'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('submission_price__gte', Decimal('0.01'))), name='order_submission_price_minimum'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_cash__gte', Decimal('0.00'))), name='order_reserved_cash_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('execution_price__isnull', True), ('execution_price__gte', Decimal('0.01')), _connector='OR'), name='order_execution_price_minimum'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('portfolio', 'stock'), name='unique_holding_per_portfolio_stock'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='reserved_quantity_not_exceed_quantity'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', Decimal('0.00')), _negated=True), name='cash_transaction_amount_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', Decimal('0.00'))), name='cash_transaction_balance_after_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', Decimal('0.00')), ('transaction_type__in', ['INITIAL_BALANCE', 'DEPOSIT', 'SALE'])), models.Q(('amount__lt', Decimal('0.00')), ('transaction_type__in', ['WITHDRAWAL', 'PURCHASE'])), _connector='OR'), name='cash_transaction_amount_sign_matches_type'),
        ),
    ]
