# Generated by Django 5.2.17 on 2026-09-29 22:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('cash_balance__gte', Decimal('0.00'))), name='cash_balance_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_cash__gte', Decimal('0.00'))), name='reserved_cash_not_negative'),
        ),
    ]
