# Generated by Django 5.2.17 on 2026-09-29 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_pricehistory'),
        ('trading', '0002_portfolio_cash_balance_not_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trading.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='market.stock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'stock'), name='unique_holding_per_portfolio_stock'), models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='reserved_quantity_not_exceed_quantity')],
            },
        ),
    ]
