# Generated by Django 5.2.17 on 2026-10-03 13:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_pricehistory'),
        ('trading', '0005_cashtransaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', Decimal('0.00'))), name='cash_transaction_balance_after_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', Decimal('0.00')), ('transaction_type__in', ['INITIAL_BALANCE', 'DEPOSIT', 'SALE'])), models.Q(('amount__lt', Decimal('0.00')), ('transaction_type__in', ['WITHDRAWAL', 'PURCHASE'])), _connector='OR'), name='cash_transaction_amount_sign_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('submission_price__gte', Decimal('0.01'))), name='order_submission_price_minimum'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_cash__gte', Decimal('0.00'))), name='order_reserved_cash_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('execution_price__isnull', True), ('execution_price__gte', Decimal('0.01')), _connector='OR'), name='order_execution_price_minimum'),
        ),
    ]
