# Generated by Django 5.2.17 on 2026-09-19 18:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid stock symbol.', regex='^[A-Za-z][A-Za-z0-9.-]*$')])),
                ('company_name', models.CharField(max_length=200)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_price__gte', Decimal('0.01'))), name='stock_price_at_least_one_cent')],
            },
        ),
    ]
