# Generated by Django 5.2.17 on 2026-09-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_closed', models.BooleanField(default=True)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('closes_at__isnull', True), ('is_closed', True), ('opens_at__isnull', True)), models.Q(('closes_at__isnull', False), ('is_closed', False), ('opens_at__isnull', False), ('closes_at__gt', models.F('opens_at'))), _connector='OR'), name='valid_market_exception_hours')],
            },
        ),
    ]
