# Generated by Django 5.2.17 on 2026-09-26 20:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('percentage_change', models.DecimalField(decimal_places=4, max_digits=8)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='market.stock')),
            ],
            options={
                'ordering': ['-effective_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('previous_price__gte', Decimal('0.01'))), name='history_previous_price_at_least_one_cent'), models.CheckConstraint(condition=models.Q(('new_price__gte', Decimal('0.01'))), name='history_new_price_at_least_one_cent')],
            },
        ),
    ]
